format = """
$git_branch\
$git_status\
$directory\
"""

# Disable the blank line at the start of the prompt
add_newline = false

[directory]
format = "[  $path ]($style)"
truncation_length = 2
truncation_symbol = ""

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
format = '[ $symbol $branch ]($style)'

[git_status]
format = '[$all_status$ahead_behind ]($style)'
